language: php

php:
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - composer test

# Monitor only these branches
branches:
  only:
    - main
